In [41]:

# Carregar os Dados 

import pandas as pd
import numpy as np


df_base = pd.read_csv('clientes_financeiro.csv', sep=',' ,low_memory=False)

df_base

,id_cliente,nome,idade,renda_mensal,limite_credito,gasto_mensal,parcelas_em_aberto,status_pagamento,cidade
0,1,Ana Silva,28,3500.0,8000.0,2100.0,2,Em dia,São Paulo
1,2,Bruno costa,35,5200.0,12000.0,9800.0,5,Atrasado,Rio de Janeiro
2,3,Carlos Mendes,42,8000.0,20000.0,4500.0,1,Em dia,Belo Horizonte
3,4,Daniela Souza,31,2800.0,6000.0,5900.0,8,Inadimplente,São Paulo
4,5,Eduardo Lima,55,12000.0,30000.0,8000.0,0,Em dia,Curitiba
5,6,Fernanda Rocha,27,2200.0,4000.0,3900.0,6,Atrasado,São Paulo
6,7,Gabriel Martins,39,6500.0,15000.0,6200.0,2,Em dia,Porto Alegre
7,8,Helena Castro,45,9000.0,22000.0,11000.0,4,Atrasado,Rio de Janeiro
8,9,Igor Teixeira,33,4100.0,9000.0,8800.0,9,Inadimplente,São Paulo
9,10,Julia Ferreira,29,3800.0,8500.0,2000.0,0,Em dia,Campinas
10,11,Kevin alves,47,7200.0,18000.0,5400.0,1,Em dia,Belo Horizonte
11,12,Larissa Nunes,26,2500.0,5000.0,4800.0,7,Inadimplente,São Paulo
12,13,Marcos Oliveira,52,11000.0,25000.0,7000.0,0,Em dia,Curitiba
13,14,Natalia Pires,36,5800.0,13000.0,12800.0,6,Atrasado,Rio de Janeiro
14,15,Otavio Ramos,41,7500.0,17000.0,3200.0,1,Em dia,São Paulo
15,16,Patricia Gomes,30,3200.0,7000.0,6900.0,8,Inadimplente,Campinas
16,17,Rafael barbosa,38,6000.0,14000.0,5500.0,2,Em dia,Porto Alegre
17,18,Sabrina Dias,44,8500.0,21000.0,9000.0,3,Em dia,São Paulo
18,19,Thiago Cardoso,25,2000.0,3500.0,3400.0,7,Atrasado,Rio de Janeiro
19,20,Ursula Monteiro,50,10000.0,24000.0,6000.0,0,Em dia,Belo Horizonte

In [42]:
# inspecionando os Dados 

display(df_base.shape)    # 20,9
display(df_base.dtypes) 
#display(df_base.describe())

(20, 9)

id_cliente              int64
nome                      str
idade                   int64
renda_mensal          float64
limite_credito        float64
gasto_mensal          float64
parcelas_em_aberto      int64
status_pagamento          str
cidade                    str
dtype: object

In [43]:
df_analise = df_base

In [44]:
# padronização

df_analise['nome'] = df_analise['nome'].str.strip().str.title()

In [45]:
df_analise

,id_cliente,nome,idade,renda_mensal,limite_credito,gasto_mensal,parcelas_em_aberto,status_pagamento,cidade
0,1,Ana Silva,28,3500.0,8000.0,2100.0,2,Em dia,São Paulo
1,2,Bruno Costa,35,5200.0,12000.0,9800.0,5,Atrasado,Rio de Janeiro
2,3,Carlos Mendes,42,8000.0,20000.0,4500.0,1,Em dia,Belo Horizonte
3,4,Daniela Souza,31,2800.0,6000.0,5900.0,8,Inadimplente,São Paulo
4,5,Eduardo Lima,55,12000.0,30000.0,8000.0,0,Em dia,Curitiba
5,6,Fernanda Rocha,27,2200.0,4000.0,3900.0,6,Atrasado,São Paulo
6,7,Gabriel Martins,39,6500.0,15000.0,6200.0,2,Em dia,Porto Alegre
7,8,Helena Castro,45,9000.0,22000.0,11000.0,4,Atrasado,Rio de Janeiro
8,9,Igor Teixeira,33,4100.0,9000.0,8800.0,9,Inadimplente,São Paulo
9,10,Julia Ferreira,29,3800.0,8500.0,2000.0,0,Em dia,Campinas
10,11,Kevin Alves,47,7200.0,18000.0,5400.0,1,Em dia,Belo Horizonte
11,12,Larissa Nunes,26,2500.0,5000.0,4800.0,7,Inadimplente,São Paulo
12,13,Marcos Oliveira,52,11000.0,25000.0,7000.0,0,Em dia,Curitiba
13,14,Natalia Pires,36,5800.0,13000.0,12800.0,6,Atrasado,Rio de Janeiro
14,15,Otavio Ramos,41,7500.0,17000.0,3200.0,1,Em dia,São Paulo
15,16,Patricia Gomes,30,3200.0,7000.0,6900.0,8,Inadimplente,Campinas
16,17,Rafael Barbosa,38,6000.0,14000.0,5500.0,2,Em dia,Porto Alegre
17,18,Sabrina Dias,44,8500.0,21000.0,9000.0,3,Em dia,São Paulo
18,19,Thiago Cardoso,25,2000.0,3500.0,3400.0,7,Atrasado,Rio de Janeiro
19,20,Ursula Monteiro,50,10000.0,24000.0,6000.0,0,Em dia,Belo Horizonte

In [ ]:
# Tratamento dos Dados 


df_analise['limite_disponivel'] = df_analise['gasto_mensal'] / df_analise['limite_credito']
df_analise

,id_cliente,nome,idade,renda_mensal,limite_credito,gasto_mensal,parcelas_em_aberto,status_pagamento,cidade,limite_disponivel
0,1,Ana Silva,28,3500.0,8000.0,2100.0,2,Em dia,São Paulo,0.262500
1,2,Bruno Costa,35,5200.0,12000.0,9800.0,5,Atrasado,Rio de Janeiro,0.816667
2,3,Carlos Mendes,42,8000.0,20000.0,4500.0,1,Em dia,Belo Horizonte,0.225000
3,4,Daniela Souza,31,2800.0,6000.0,5900.0,8,Inadimplente,São Paulo,0.983333
4,5,Eduardo Lima,55,12000.0,30000.0,8000.0,0,Em dia,Curitiba,0.266667
5,6,Fernanda Rocha,27,2200.0,4000.0,3900.0,6,Atrasado,São Paulo,0.975000
6,7,Gabriel Martins,39,6500.0,15000.0,6200.0,2,Em dia,Porto Alegre,0.413333
7,8,Helena Castro,45,9000.0,22000.0,11000.0,4,Atrasado,Rio de Janeiro,0.500000
8,9,Igor Teixeira,33,4100.0,9000.0,8800.0,9,Inadimplente,São Paulo,0.977778
9,10,Julia Ferreira,29,3800.0,8500.0,2000.0,0,Em dia,Campinas,0.235294
10,11,Kevin Alves,47,7200.0,18000.0,5400.0,1,Em dia,Belo Horizonte,0.300000
11,12,Larissa Nunes,26,2500.0,5000.0,4800.0,7,Inadimplente,São Paulo,0.960000
12,13,Marcos Oliveira,52,11000.0,25000.0,7000.0,0,Em dia,Curitiba,0.280000
13,14,Natalia Pires,36,5800.0,13000.0,12800.0,6,Atrasado,Rio de Janeiro,0.984615
14,15,Otavio Ramos,41,7500.0,17000.0,3200.0,1,Em dia,São Paulo,0.188235
15,16,Patricia Gomes,30,3200.0,7000.0,6900.0,8,Inadimplente,Campinas,0.985714
16,17,Rafael Barbosa,38,6000.0,14000.0,5500.0,2,Em dia,Porto Alegre,0.392857
17,18,Sabrina Dias,44,8500.0,21000.0,9000.0,3,Em dia,São Paulo,0.428571
18,19,Thiago Cardoso,25,2000.0,3500.0,3400.0,7,Atrasado,Rio de Janeiro,0.971429
19,20,Ursula Monteiro,50,10000.0,24000.0,6000.0,0,Em dia,Belo Horizonte,0.250000

In [ ]:
# trocando o nome da coluna 

df_analise = df_analise.rename(columns={'limite_disponivel' : 'taxa_utilizacao'})
df_analise

,id_cliente,nome,idade,renda_mensal,limite_credito,gasto_mensal,parcelas_em_aberto,status_pagamento,cidade,taxa_utilizacao
0,1,Ana Silva,28,3500.0,8000.0,2100.0,2,Em dia,São Paulo,0.262500
1,2,Bruno Costa,35,5200.0,12000.0,9800.0,5,Atrasado,Rio de Janeiro,0.816667
2,3,Carlos Mendes,42,8000.0,20000.0,4500.0,1,Em dia,Belo Horizonte,0.225000
3,4,Daniela Souza,31,2800.0,6000.0,5900.0,8,Inadimplente,São Paulo,0.983333
4,5,Eduardo Lima,55,12000.0,30000.0,8000.0,0,Em dia,Curitiba,0.266667
5,6,Fernanda Rocha,27,2200.0,4000.0,3900.0,6,Atrasado,São Paulo,0.975000
6,7,Gabriel Martins,39,6500.0,15000.0,6200.0,2,Em dia,Porto Alegre,0.413333
7,8,Helena Castro,45,9000.0,22000.0,11000.0,4,Atrasado,Rio de Janeiro,0.500000
8,9,Igor Teixeira,33,4100.0,9000.0,8800.0,9,Inadimplente,São Paulo,0.977778
9,10,Julia Ferreira,29,3800.0,8500.0,2000.0,0,Em dia,Campinas,0.235294
10,11,Kevin Alves,47,7200.0,18000.0,5400.0,1,Em dia,Belo Horizonte,0.300000
11,12,Larissa Nunes,26,2500.0,5000.0,4800.0,7,Inadimplente,São Paulo,0.960000
12,13,Marcos Oliveira,52,11000.0,25000.0,7000.0,0,Em dia,Curitiba,0.280000
13,14,Natalia Pires,36,5800.0,13000.0,12800.0,6,Atrasado,Rio de Janeiro,0.984615
14,15,Otavio Ramos,41,7500.0,17000.0,3200.0,1,Em dia,São Paulo,0.188235
15,16,Patricia Gomes,30,3200.0,7000.0,6900.0,8,Inadimplente,Campinas,0.985714
16,17,Rafael Barbosa,38,6000.0,14000.0,5500.0,2,Em dia,Porto Alegre,0.392857
17,18,Sabrina Dias,44,8500.0,21000.0,9000.0,3,Em dia,São Paulo,0.428571
18,19,Thiago Cardoso,25,2000.0,3500.0,3400.0,7,Atrasado,Rio de Janeiro,0.971429
19,20,Ursula Monteiro,50,10000.0,24000.0,6000.0,0,Em dia,Belo Horizonte,0.250000

In [92]:
# análise pela taxa de utilizacao (limite credito)

df_analise['taxa_utilizacao'] = df_analise['taxa_utilizacao']

df_risco = df_analise[df_analise['taxa_utilizacao'] > 0.8]
display(df_risco[['nome', 'cidade', 'status_pagamento', 'taxa_utilizacao']])

              nome          cidade status_pagamento  taxa_utilizacao
1      Bruno Costa  Rio de Janeiro         Atrasado         0.816667
3    Daniela Souza       São Paulo     Inadimplente         0.983333
5   Fernanda Rocha       São Paulo         Atrasado         0.975000
8    Igor Teixeira       São Paulo     Inadimplente         0.977778
11   Larissa Nunes       São Paulo     Inadimplente         0.960000
13   Natalia Pires  Rio de Janeiro         Atrasado         0.984615
15  Patricia Gomes        Campinas     Inadimplente         0.985714
18  Thiago Cardoso  Rio de Janeiro         Atrasado         0.971429

In [93]:
# colocando em ordem decrescente pela utilização 

display(df_risco[['nome', 'cidade', 'status_pagamento', 'taxa_utilizacao']].sort_values(by='taxa_utilizacao' , ascending= False))

              nome          cidade status_pagamento  taxa_utilizacao
15  Patricia Gomes        Campinas     Inadimplente         0.985714
13   Natalia Pires  Rio de Janeiro         Atrasado         0.984615
3    Daniela Souza       São Paulo     Inadimplente         0.983333
8    Igor Teixeira       São Paulo     Inadimplente         0.977778
5   Fernanda Rocha       São Paulo         Atrasado         0.975000
18  Thiago Cardoso  Rio de Janeiro         Atrasado         0.971429
11   Larissa Nunes       São Paulo     Inadimplente         0.960000
1      Bruno Costa  Rio de Janeiro         Atrasado         0.816667

In [96]:
# analise por inadiplente 



df_inadimplente = df_analise[df_analise['status_pagamento'] == 'Inadimplente']

display(df_inadimplente[['nome', 'idade', 'renda_mensal','cidade']])
display(df_inadimplente[['idade', 'renda_mensal']].mean())

              nome  idade  renda_mensal     cidade
3    Daniela Souza     31        2800.0  São Paulo
8    Igor Teixeira     33        4100.0  São Paulo
11   Larissa Nunes     26        2500.0  São Paulo
15  Patricia Gomes     30        3200.0   Campinas

idade             30.0
renda_mensal    3150.0
dtype: float64

In [97]:
df_analise.to_csv('clientes_financeiro_analisado.csv', index=False)
df_risco.to_csv('clientes_risco_e_inadimplencia.csv', index=False)
print('Arquivo Salvo com sucesso')

Arquivo Salvo com sucesso